version: '3.8'

services:
  app:
    container_name: hospital_appointment_app
    build: .
    restart: always
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
      
  db:
    container_name: hospital_appointment_db
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data